spring:
  jpa:
    hibernate:
      ddl-auto: create-drop
#  autoconfigure:
#    exclude: org.springframework.boot.autoconfigure.security.servlet.SecurityAutoConfiguration
#ribbon:
#  IsSecure: false

#security:
#  basic:
#    enabled: false
#
#management:
#  security:
#    enabled: false

---

spring:
  profiles: default
  jpa:
    database: HSQL

---

spring:
  profiles: pcf
  jpa:
    database: MYSQL

---

spring:
  profiles: pws
  jpa:
    database: POSTGRESQL
